apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pizza-app
  template:
    metadata:
      labels:
        app: pizza-app
    spec:
      containers:
      - name: pizza-container
        image: 270313859272.dkr.ecr.us-west-2.amazonaws.com/my-pizza-app-repo:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: aws-logging
